on: push

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build
        run: dotnet build ./src/NGherkin.sln

      - name: Test
        run: dotnet test --no-build --no-restore ./src/NGherkin.sln
