on: push

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build
        run: dotnet build ./src/NGherkin.sln

      - name: Test
        run: dotnet test --no-build --no-restore ./src/NGherkin.sln
